SELECT DATEFROMPARTS(YEAR(MRRECVH.RECV_DATE),MONTH(MRRECVH.RECV_DATE), DAY(MRRECVH.RECV_DATE)) as 'Date', MRRECVH.RECV_DATE, MRRECVD.CONTROL, SUBSTRING(MRRECVD.CONTROL, 9, 2) as 'ADJ',
MRRECVD.LINE_TYPE,
MRRECVD.SEQUENCE,
MRRECVD.ACCOUNT, 
MRRECVD.COMMODITY, MRRECVD.YARD, MRRECVD.DESCRIPTION,
MRRECVD.SETL_NET, MRRECVD.SETL_PRICE, MRRECVD.SETL_UM, MRRECVD.SETL_AMOUNT,
PPPrice.EFFECTIVE_DATE, PPPrice.EXPIRE_DATE, PPPrice.DESCRIPTION, 
PPPrice.MARKET, PPPrice.MARKET_COMM, PPPrice.MARKET_BASE, PPPrice.DIFF_AMOUNT1, PPPrice.DIFF_PERCENT, PPPrice.DIFF_AMOUNT2, PPPrice.PRICE, PPPrice.PRICE_UM, PPPrice.COMMENT,
PPMKTD.EFFECTIVE_DATE, PPMKTD.LOW_PRICE, PPMKTD.HIGH_PRICE, PPMKTD.PRICE_UM, PPMKTD.DESCRIPTION
FROM MRRECVD INNER JOIN MRRECVH
on
MRRECVD.COMPANY = MRRECVH.COMPANY and
MRRECVD.DIVISION = MRRECVH.DIVISION and
MRRECVD.CONTROL = MRRECVH.CONTROL
left outer join PPPrice
on
MRRECVD.COMPANY = PPPrice.COMPANY and
MRRECVD.DIVISION = PPPrice.DIVISION and
MRRECVD.ACCOUNT = PPPrice.ACCOUNT and
MRRECVD.COMMODITY = PPPrice.COMMODITY and
MRRECVD.YARD = PPPrice.YARD and
MRRECVH.RECV_DATE between PPPrice.EFFECTIVE_DATE AND COALESCE(PPPrice.EXPIRE_DATE, '9999-12-31')
left outer join PPMKTD
on
MRRECVD.COMPANY = PPMKTD.COMPANY and
MRRECVD.DIVISION = PPMKTD.DIVISION and
PPPrice.MARKET_COMM = PPMKTD.COMMODITY and
PPPrice.MARKET = PPMKTD.MARKET and
DATEFROMPARTS(YEAR(MRRECVH.RECV_DATE),MONTH(MRRECVH.RECV_DATE),1) = PPMKTD.EFFECTIVE_DATE
where 
MRRECVH.RECV_DATE > '2019-01-01'  
order by CONTROL, LINE_TYPE, SEQUENCE

